# Generated by Django 5.1.1 on 2024-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.thefuzzyduck.co.uk%2Fshop%2Fsavouries%2Fsweet-potato-feta-jalapeno-free-range-scotch-egg%2F&psig=AOvVaw2EulhYF8a-ZJbJMJB-vZDC&ust=1732295390551000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCPD92q717YkDFQAAAAAdAAAAABAE', max_length=500),
        ),
    ]
