# Generated by Django 5.1.1 on 2024-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_full_description',
            field=models.TextField(null=True),
        ),
    ]
