# Generated by Django 5.1.1 on 2024-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.CharField(max_length=200, verbose_name='Pakkumise lühikirjeldus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_full_description',
            field=models.TextField(null=True, verbose_name='Pakkumise täiskirjeldus'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(upload_to='items/', verbose_name='Pakkumise pilt'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='Pakkumise nimi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(verbose_name='Pakkumise hind'),
        ),
    ]
