# Generated by Django 5.1.1 on 2024-11-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_item_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_full_description',
            field=models.TextField(verbose_name='Pakkumise täiskirjeldus'),
        ),
    ]
